# Generated by Django 4.0.5 on 2022-06-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_mobilenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=150)),
                ('LastName', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('Username', models.CharField(max_length=150)),
                ('DateOfBirth', models.CharField(max_length=150)),
                ('ProfilePhoto', models.FileField(default='DefaultPhotos/boy_avatar.jpg', upload_to='DoctorPhotos/')),
                ('MobileNumber', models.CharField(default='Not available', max_length=13)),
                ('DoctorLicense', models.FileField(upload_to='DoctorDocuments/')),
                ('YearsOfExperience', models.IntegerField(default=0)),
                ('Rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('Ratings_stars', models.CharField(blank=True, default='', max_length=5)),
                ('non_stars', models.CharField(default='12345', max_length=5)),
                ('Ratings_count', models.IntegerField(default=0)),
                ('Education', models.CharField(default='Not available', max_length=250)),
                ('Masters', models.CharField(default='Not available', max_length=250)),
                ('HospitalName', models.CharField(max_length=50)),
                ('HospitalRegisterationNumber', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.IntegerField(choices=[(1, 'Andhra Pradesh'), (2, 'Arunachal Pradesh'), (3, 'Assam'), (4, 'Bihar'), (5, 'Chhattisgarh'), (6, 'Goa'), (7, 'Gujarat'), (8, 'Haryana'), (9, 'Himachal Pradesh'), (10, 'Jharkhand'), (11, 'Karnataka'), (12, 'Kerala'), (13, 'Madhya Pradesh'), (14, 'Maharashtra'), (15, 'Manipur'), (16, 'Meghalaya'), (17, 'Mizoram'), (18, 'Nagaland'), (19, 'Odisha'), (20, 'Punjab'), (21, 'Rajasthan'), (22, 'Sikkim'), (23, 'Tamil Nadu'), (24, 'Telangana'), (25, 'Tripura'), (26, 'Uttarakhand'), (27, 'Uttar Pradesh'), (28, 'West Bengal'), (29, 'All')], default=1)),
                ('Pincode', models.CharField(max_length=20)),
                ('Department', models.IntegerField(choices=[(1, 'General Health'), (2, 'Cardiology'), (3, 'Dental'), (4, 'Medical Research'), (5, 'Emergency'), (6, 'Gynecologist'), (7, 'All')], default=1)),
                ('Description', models.CharField(default='Dear, be strong because your life will be better now. Time does not remain same. You will get well soon!', max_length=150)),
                ('Achievements1', models.CharField(default='No achievements added recently', max_length=50)),
                ('Achievements2', models.CharField(default='No achievements added recently', max_length=50)),
                ('Achievements3', models.CharField(default='No achievements added recently', max_length=50)),
                ('Achievements4', models.CharField(default='No achievements added recently', max_length=50)),
            ],
        ),
    ]
